{% set name = "jupyterlab_autoversion" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8260e3fb58d9c4166d4c45a32a9cd8f792f0ed968be7c9c0fa9b887d0933032

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >={{ python_min }}
    - gitpython >=2.1.11
    - jupyterlab >=4,<5
    - nbdime

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyterlab_autoversion

about:
  home: http://github.com/timkpaine/jupyterlab_autoversion
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Automatically version jupyter notebooks on save
  description: Automatically version jupyter notebooks on save
  dev_url: https://github.com/timkpaine/jupyterlab_autoversion

extra:
  recipe-maintainers:
    - timkpaine
