{% set name = "jupyterlab_autoversion" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28ba91a40769c53d1b4833c304096c0dfc5e9515ae06f8d35b4ab5055bd7f70f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - yarn
    - jupyter-packaging
    - jupyterlab >=3.0.0
  run:
    - python >=3.7
    - gitpython >=2.1.11

test:
  imports:
    - jupyterlab_autoversion

about:
  home: http://github.com/timkpaine/jupyterlab_autoversion
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Automatically version jupyter notebooks on save

  description: |
    Automatically version jupyter notebooks on save
  dev_url: https://github.com/timkpaine/jupyterlab_autoversion

extra:
  recipe-maintainers:
    - timkpaine
