{% set name = "jupyterlab_autoversion" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ddf52d9907768e441a2fd6e65bfd2a9e66187e3e48b37fefa46739824e9f058

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - yarn
    - jupyter-packaging
    - jupyterlab >=3.0.0
  run:
    - python >=3.7
    - gitpython >=2.1.11
    - jupyterlab >=3.0.0
    - notebook

test:
  imports:
    - jupyterlab_autoversion

about:
  home: http://github.com/timkpaine/jupyterlab_autoversion
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Automatically version jupyter notebooks on save

  description: |
    Automatically version jupyter notebooks on save
  dev_url: https://github.com/timkpaine/jupyterlab_autoversion

extra:
  recipe-maintainers:
    - timkpaine
